# Generated by Django 4.1.11 on 2023-09-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date_published', models.DateTimeField()),
                ('date_pulled', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('website', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('sentiment', models.CharField(default='Neutro', max_length=15)),
            ],
        ),
    ]
