# Generated by Django 4.1.11 on 2023-10-02 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="date_published",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="news",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("POSITIVO", "Positivo"),
                    ("NEUTRO", "Neutro"),
                    ("NEGATIVO", "Negativo"),
                ],
                default="Neutro",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="news",
            index=models.Index(
                fields=["date_published"], name="news_news_date_pu_0e98dc_idx"
            ),
        ),
    ]
